name: Docker Swagger-Codegen v3

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Laserfiche API SDK
      run: docker run -v /API_GEN:/local swaggerapi/swagger-codegen-cli-v3 generate -i 'https://api.laserfiche.com/repository/swagger/v1-alpha/swagger.json' --http-user-agent "Chrome/91.0.4472.106" -l python -o /local/laserfiche_api -DpackageName=laserfiche_api
    
    - uses: actions/upload-artifact@v2
      with: 
        name: laserfiche_api
        path: /API_GEN/laserfiche_api
        if-no-files-found: error
    

