name: Docker Swagger-Codegen v3

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Laserfiche API SDK
      run: docker run -v /API_GEN:/local swaggerapi/swagger-codegen-cli-v3 generate -i 'https://api.laserfiche.com/repository/swagger/v1-alpha/swagger.json' --http-user-agent "Chrome/91.0.4472.106" -l python -o /local/laserfiche_api -DpackageName=laserfiche_api
    
    - uses: actions/upload-artifact@v2
      name: Save artifact
      with: 
        name: laserfiche_api
        path: /API_GEN/laserfiche_api
        if-no-files-found: error
        
    - uses: actions/upload-release-asset@v1
      name: upload laserfiche_api
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: https://github.com/Layer8Err/laserfiche_api/dist
        artifact: laserfiche_api
        asset_content_type: application/zip
        asset_path: /dist/
        
#     - uses: actions/create-release@v1
#       name: Create release
#       with:
#         draft: false
#         prerelease: false
#         release_name: latest
#         tag_name: ${{ github.ref }}
#         body_
      
    
#     - uses: pypa/gh-action-pypi-publish@release/v1
#       with:
#         user: __token__
#         password: ${{ secrets.PYPI_API_TOKEN }}

