name: Docker Swagger-Codegen v3

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Laserfiche API SDK
      run: docker run -v /API_GEN:/local swaggerapi/swagger-codegen-cli-v3 generate -i 'https://api.laserfiche.com/repository/swagger/v1-alpha/swagger.json' --http-user-agent "Chrome/91.0.4472.106" -l python -o /local/laserfiche-api -DpackageName=laserfiche-api
        
    - name: Compress artifact for PyPi
      run: tar -czvf /tmp/laserfiche-api.tar.gz -C /API_GEN laserfiche-api
      
    - uses: actions/upload-artifact@v2
      name: Save artifact
      with: 
        name: laserfiche-api
        path: /tmp/laserfiche-api.tar.gz
        if-no-files-found: error
                
#     - uses: actions/create-release@v1
#       name: Create release
#       with:
#         draft: false
#         prerelease: false
#         release_name: latest
#         tag_name: ${{ github.ref }}
#         body_
      
    
    - uses: pypa/gh-action-pypi-publish@release/v1
      name: Publish to PyPi
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}

